[package]
name = "Rusty-A11y"
version = "0.1.0"
authors = [
    "TheBoatyMcBoatFace <bentley.hensel@civicactions.com>",
    "CivicActions",
    "https://civicactions.com"
]
edition = "2021"

[dependencies]
rocket = "0.5.0"
reqwest = "0.11.0"
google-bigquery2 = "4.0.1+20220222"
serde_derive = "1.0.0"
rocket_contrib = { version = "0.5.0", default-features = false, features = ["json"] }

[dependencies.rocket_codegen]
version = "0.5.0"
features = ["serve", "json"]