[package]
name = "Rusty-A11y"
version = "0.1.0"
authors = [
    "TheBoatyMcBoatFace <bentley.hensel@civicactions.com>",
    "CivicActions",
    "https://civicactions.com"
]
edition = "2021"

[dependencies]
rocket = "0.4.11"
reqwest = "0.11.14"
gcp-bigquery-client = "0.16.4"
serde_derive = "1.0.152"
rocket_contrib = { version = "0.5.0", default-features = false, features = ["json"] }

[dependencies.rocket_codegen]
version = "0.4.11"
features = ["serve", "json"]