[global]
address = "0.0.0.0"
port = 8080
workers = 4
keep_alive = 5

[development]
address = "0.0.0.0"
port = 8080

[staging]
address = "0.0.0.0"
port = 8080

[production]
address = "0.0.0.0"
port = 8080