name: Build and Publish Rust Containers

on:
  push:
    branches:
      - main

  workflow_dispatch:

# Set environment variables for the container registry and image name
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Set as current repo. Can change to alternate if these shifted to another location.

jobs:
  build-and-publish:
    name: Build and Publish Docker Container(s)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/login-action
      #      - name: Log in to Docker Hub
      #        uses: docker/login-action@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_KEY=API-Key-Here
            GOOGLE_PROJECT_ID=Project-ID
            GOOGLE_DATASET=GOOGLE_DATASET
            A11Y_URL=A11Y_URL
            A11Y_JWT=
            GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS_PATH

  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

  deploy:
    name: Deploy to Namespace
    needs: build-and-publish
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - name: Deploy
        run: kubectl apply --namespace=public-sector-a11y_connect -f k8s
